name: Magipoka Tests

on:
  pull_request:
    branches:
      - main
      - develop
    types: [opened, synchronize]

env:
  YARN_CACHE_FOLDER: .cache/yarn

jobs:
  setup:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: ["16"]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Apply cache
        id: yarn-cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Install node_modules
        run: yarn --frozen-lockfile

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ matrix.os }}-node-v${{ matrix.node }}-${{ github.sha }}

  lint:
    needs: setup
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: ["16"]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Apply cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ matrix.os }}-node-v${{ matrix.node }}-${{ github.sha }}

      - name: Run lint
        run: yarn run lint

  test:
    needs: setup
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: ["16"]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Apply cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ matrix.os }}-node-v${{ matrix.node }}-${{ github.sha }}

      - name: Run tests
        run: yarn run test
